[package]
name = "lambda-otel-utils"
version = "0.3.1"
edition = "2021"
authors = ["Alessandro Bologna <alessandro.bologna@gmail.com>"]
license = "MIT"
rust-version = "1.80"
description = "OpenTelemetry utilities for AWS Lambda (DEPRECATED)"
repository = "https://github.com/dev7a/package-archive/tree/main/packages/rust/lambda-otel-utils"
homepage = "https://github.com/dev7a/package-archive"
keywords = ["opentelemetry", "otlp", "aws", "lambda", "telemetry"]
categories = ["development-tools::debugging", "development-tools::profiling"]

[[example]]
name = "tracing_example"
path = "examples/tracing_example.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
opentelemetry = { version = "0.28.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.28.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.28.0", features = ["http-proto", "http-json", "reqwest-client"] }
opentelemetry-http = { version = "0.28.0" }
tracing = { version = "0.1", features = ["log"] }
tracing-opentelemetry = "0.29.0"
lambda_runtime = "0.11.0"
otlp-stdout-client = { version = "0.4.1", path = "../otlp-stdout-client" }
thiserror = "1.0.68"
pin-project = "1.1.0"
opentelemetry-aws = { version = "0.16.0", features = ["detector-aws-lambda"] }
opentelemetry-semantic-conventions = { version = "0.28.0", features = ["semconv_experimental"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "env-filter", "json"] }
rustc_version_runtime = "0.3.0"

[dev-dependencies]
sealed_test = "1.1.0"   
doc-comment = "0.3"
serde_json = "1.0.133"
reqwest = { version = "0.12.5", features = ["json"] }
aws_lambda_events = { version = "0.15.0", default-features = false, features = ["apigw"] }
